// GENERATED FILE -- do not edit by hand.
// Demo incident manifest: host inventory, entity inventory and the narrative the rows encode.
// Regenerate with:  node scripts/gen-demo-dataset.mjs
//
// SYNTHETIC DATA ONLY. Every host, account, address, domain and hash below is
// invented: RFC 5737 documentation IP ranges, the RFC 2606 reserved .example
// TLD, and hashes derived from fixed labels. No real host was ever collected.
// See docs/DEMO.md.

export const manifest = {
  "id": "irtriage-demo-incident-2026-03",
  "schema_version": "1.0.0",
  "title": "Demo incident: phishing to forest-root compromise and data exfiltration",
  "synthetic": true,
  "synthetic_notice": "SYNTHETIC DATA ONLY. Generated by scripts/gen-demo-dataset.mjs. Every host, account, IP address, domain and file hash is invented; external addresses come from the RFC 5737 documentation ranges and every DNS name uses the RFC 2606 reserved .example TLD. This payload contains no real host data and is safe to publish.",
  "generated_by": "scripts/gen-demo-dataset.mjs",
  "platform": "windows",
  "environment": {
    "forest": "corp.example",
    "domains": [
      {
        "dns": "corp.example",
        "netbios": "CORP",
        "role": "forest root domain"
      },
      {
        "dns": "eu.corp.example",
        "netbios": "EU",
        "role": "child domain (parent/child transitive trust to corp.example)"
      }
    ],
    "trust": "eu.corp.example -> corp.example (parent/child, transitive, two-way)",
    "note": "One forest, two domains - the shape of the GOAD-Light lab this demo stands in for. Three hosts were collected: the forest-root domain controller, a child-domain member server and a child-domain workstation. The child-domain controller DC-EU-01 (10.0.5.10) is referenced by evidence but was NOT collected, which is normal for a scoped triage."
  },
  "collection_window": {
    "start_utc": "2026-03-07T00:00:00.0000000Z",
    "end_utc": "2026-03-15T00:00:00.0000000Z"
  },
  "row_count": 2387,
  "detection_row_count": 49,
  "files": [
    {
      "id": "wks-corp-01",
      "host": "WKS-CORP-01",
      "host_id": "4f1c0a9e-0001-4a00-9c31-b0de51000001",
      "domain": "eu.corp.example",
      "os": "Windows 11 Pro 23H2",
      "role": "Finance workstation in the child domain (patient zero)",
      "ip": "10.0.5.41",
      "module": "./host-wks-corp-01.js",
      "file_name": "WKS-CORP-01-demo.jsonl",
      "row_count": 940,
      "detection_row_count": 24
    },
    {
      "id": "srv-corp-fs02",
      "host": "SRV-CORP-FS02",
      "host_id": "4f1c0a9e-0002-4a00-9c31-b0de51000002",
      "domain": "eu.corp.example",
      "os": "Windows Server 2022 Standard",
      "role": "Child-domain file server (staging, cross-domain pivot, exfiltration point)",
      "ip": "10.0.5.20",
      "module": "./host-srv-corp-fs02.js",
      "file_name": "SRV-CORP-FS02-demo.jsonl",
      "row_count": 726,
      "detection_row_count": 15
    },
    {
      "id": "dc-corp-01",
      "host": "DC-CORP-01",
      "host_id": "4f1c0a9e-0003-4a00-9c31-b0de51000003",
      "domain": "corp.example",
      "os": "Windows Server 2022 Datacenter",
      "role": "Forest-root domain controller (corp.example)",
      "ip": "10.0.10.10",
      "module": "./host-dc-corp-01.js",
      "file_name": "DC-CORP-01-demo.jsonl",
      "row_count": 721,
      "detection_row_count": 10
    }
  ],
  "entities": {
    "hosts": [
      {
        "name": "WKS-CORP-01",
        "host_id": "4f1c0a9e-0001-4a00-9c31-b0de51000001",
        "ip": "10.0.5.41",
        "os": "Windows 11 Pro 23H2",
        "domain": "eu.corp.example",
        "role": "Finance workstation in the child domain (patient zero)"
      },
      {
        "name": "SRV-CORP-FS02",
        "host_id": "4f1c0a9e-0002-4a00-9c31-b0de51000002",
        "ip": "10.0.5.20",
        "os": "Windows Server 2022 Standard",
        "domain": "eu.corp.example",
        "role": "Child-domain file server (staging, cross-domain pivot, exfiltration point)"
      },
      {
        "name": "DC-CORP-01",
        "host_id": "4f1c0a9e-0003-4a00-9c31-b0de51000003",
        "ip": "10.0.10.10",
        "os": "Windows Server 2022 Datacenter",
        "domain": "corp.example",
        "role": "Forest-root domain controller (corp.example)"
      }
    ],
    "users": [
      {
        "name": "EU\\alice",
        "role": "Finance analyst on WKS-CORP-01. Opened the lure attachment; her token was used for initial execution and domain discovery."
      },
      {
        "name": "EU\\bob",
        "role": "Child-domain IT support technician. Benign administrative activity only -- and the source of most dismissible detections."
      },
      {
        "name": "EU\\carol",
        "role": "Finance manager. Benign file-share activity only."
      },
      {
        "name": "EU\\Administrator",
        "role": "Child-domain administrator. Benign scheduled maintenance only."
      },
      {
        "name": "EU\\svc-backup",
        "role": "Child-domain backup service account. Kerberoasted, then recovered from an LSASS dump and reused for lateral movement and the cross-domain step."
      },
      {
        "name": "EU\\WKS-CORP-01$",
        "role": "Computer account of the workstation."
      },
      {
        "name": "EU\\SRV-CORP-FS02$",
        "role": "Computer account of the file server."
      },
      {
        "name": "CORP\\Administrator",
        "role": "Forest-root domain administrator. Benign maintenance only."
      },
      {
        "name": "CORP\\svc-support",
        "role": "Account CREATED BY THE ATTACKER in the FOREST ROOT domain and added to Enterprise Admins."
      },
      {
        "name": "CORP\\DC-CORP-01$",
        "role": "Computer account of the forest-root domain controller."
      },
      {
        "name": "SYSTEM",
        "role": "Local SYSTEM principal."
      },
      {
        "name": "LOCAL SERVICE",
        "role": "Local LOCAL SERVICE principal."
      },
      {
        "name": "NETWORK SERVICE",
        "role": "Local NETWORK SERVICE principal."
      }
    ],
    "internal_assets": [
      {
        "ip": "10.0.5.9",
        "label": "PRX-CORP-01 (outbound web proxy, child site)"
      },
      {
        "ip": "10.0.5.10",
        "label": "DC-EU-01 (child-domain controller -- referenced by evidence, NOT collected)"
      },
      {
        "ip": "10.0.5.15",
        "label": "JMP-CORP-01 (admin jump host)"
      },
      {
        "ip": "10.0.5.20",
        "label": "SRV-CORP-FS02 (child-domain file server, collected)"
      },
      {
        "ip": "10.0.5.41",
        "label": "WKS-CORP-01 (finance workstation, collected)"
      },
      {
        "ip": "10.0.5.42",
        "label": "WKS-CORP-02 (finance workstation, not collected)"
      },
      {
        "ip": "10.0.10.10",
        "label": "DC-CORP-01 (forest-root domain controller, collected)"
      },
      {
        "ip": "10.0.10.14",
        "label": "SRV-CORP-BK01 (backup server, root site)"
      }
    ],
    "attacker_ips": [
      {
        "ip": "192.0.2.61",
        "label": "Phishing mail relay that delivered the lure"
      },
      {
        "ip": "198.51.100.24",
        "label": "Lure download host and first-stage C2 (TLS 443)"
      },
      {
        "ip": "203.0.113.77",
        "label": "Second-stage C2 reached from SRV-CORP-FS02"
      },
      {
        "ip": "203.0.113.142",
        "label": "Exfiltration endpoint (3.4 GB outbound)"
      }
    ],
    "attacker_domains": [
      {
        "domain": "invoices.billing-portal.example",
        "label": "Lure download host"
      },
      {
        "domain": "cdn-sync-updates.example",
        "label": "First-stage C2 (update-service impersonation)"
      },
      {
        "domain": "sync-relay.example",
        "label": "Second-stage C2 reached from SRV-CORP-FS02"
      },
      {
        "domain": "files-transfer-node.example",
        "label": "Exfiltration endpoint"
      }
    ],
    "key_processes": [
      "EXCEL.EXE",
      "wscript.exe",
      "powershell.exe",
      "updatesvc.exe",
      "rundll32.exe",
      "whoami.exe",
      "net.exe",
      "nltest.exe",
      "adq.exe",
      "upd.exe",
      "kt.exe",
      "a.exe",
      "wevtutil.exe",
      "vssadmin.exe",
      "cmd.exe"
    ],
    "key_files": [
      {
        "key": "lure_xlsm",
        "file_name": "Invoice_Q1_2026.xlsm",
        "label": "Macro-enabled lure attachment",
        "sha256": "c1d85360bd6f4a15e401b4b97fd3f5d9bb99a51c73088b1fdae7129d3232b61e"
      },
      {
        "key": "dropper_js",
        "file_name": "inv8841.js",
        "label": "WScript dropper written by the macro",
        "sha256": "c03dda7b05b4325f3cee22b9557c30f620ead98104fc60ea6f3b08b1d906cb62"
      },
      {
        "key": "implant",
        "file_name": "updatesvc.exe",
        "label": "First-stage implant (also deployed as upd.exe on SRV-CORP-FS02)",
        "sha256": "d7d5201e38631d05a77cedb1130deddc29f7241c84bb689ac99c25cb66ef26c5"
      },
      {
        "key": "adq",
        "file_name": "adq.exe",
        "label": "AD enumeration utility staged in the user temp directory",
        "sha256": "362495bdb4404d73c8edf1c046ab790e45dc2b7e0972f6e0b2642f146e4c726d"
      },
      {
        "key": "roast",
        "file_name": "svcq.exe",
        "label": "Kerberos service-ticket harvesting tool",
        "sha256": "74cd297cee86867e865e4b48ed5ef485c8803748e972f3178a0eb6c2b9b57665"
      },
      {
        "key": "lsass_dmp",
        "file_name": "ls.dmp",
        "label": "LSASS process minidump",
        "sha256": "4e2861ff65eafb848dac6cb0371c782b5d7d2810766b0094712da215501ec4df"
      },
      {
        "key": "sidinj",
        "file_name": "kt.exe",
        "label": "Credential/ticket manipulation tool used for the cross-domain step",
        "sha256": "7b60f0a0b74fe4c24525a1661ad5e9ace42b2ed1449d4e53bc3deb0eb02ae263"
      },
      {
        "key": "archiver",
        "file_name": "a.exe",
        "label": "Renamed archive utility used to stage finance data",
        "sha256": "5af8d60483f1c9ed88514c036bb429677ab0e8287d9e123e12359a85b84bff44"
      },
      {
        "key": "stage_archive",
        "file_name": "fin-2026Q1.7z",
        "label": "Encrypted staging archive (3.4 GB)",
        "sha256": "e0f9e2e36d5ca08013ca6b33082e8c1ff881e3a23d278657e3e5ce585c8d81ba"
      },
      {
        "key": "procdump",
        "file_name": "procdump.exe",
        "label": "Signed Sysinternals ProcDump used legitimately by IT (dismissible detection)",
        "sha256": "d62a9037cfcf81f3341e3a386a29145a9dd9452fc4abe89611a9ea81bf5f1eac"
      }
    ]
  },
  "narrative": [
    {
      "id": "p1",
      "order": 1,
      "tactic": "Initial Access",
      "title": "Finance-themed lure downloaded and opened on WKS-CORP-01",
      "hosts": [
        "WKS-CORP-01"
      ],
      "techniques": [
        "T1566.002",
        "T1204.002"
      ],
      "start_utc": "2026-03-09T09:04:12.0000000Z",
      "end_utc": "2026-03-09T09:13:58.0000000Z",
      "summary": "EU\\alice received external mail with an SPF softfail, downloaded Invoice_Q1_2026.xlsm from invoices.billing-portal.example (first observation of that domain in the environment) and opened it in Excel. The download carries Mark-of-the-Web zone 3 and an unsigned macro-enabled document hash.",
      "evidence": [
        "16948020a627b7b9c467b0f57a7f05a7179cdd6c00fc1925db2fc9150ef5eeb8",
        "52de27b38dcdf875cb0e8c1b1a0274b0d619152a3cdaa087f3b8b0f196cd932e",
        "9cb2081b95af2908bafaf4d5de40d32f2cf60b4b79661adb7025d973958c3711",
        "18228214edd3328111d38af0435710ea7f3362e56aab90dce2012ed820957ee6"
      ]
    },
    {
      "id": "p2",
      "order": 2,
      "tactic": "Execution",
      "title": "Macro chain drops a loader that beacons to cdn-sync-updates.example",
      "hosts": [
        "WKS-CORP-01"
      ],
      "techniques": [
        "T1059.007",
        "T1059.001",
        "T1027",
        "T1105",
        "T1071.001",
        "T1573.001"
      ],
      "start_utc": "2026-03-09T09:14:02.0000000Z",
      "end_utc": "2026-03-09T09:18:22.0000000Z",
      "summary": "EXCEL.EXE spawned wscript.exe running a dropped JScript file, which launched hidden encoded PowerShell. PowerShell retrieved updatesvc.exe into %APPDATA%\\Sync and ran it; the implant then established 60-second-interval sessions to 198.51.100.24:443. The full parent chain EXCEL.EXE -> wscript.exe -> powershell.exe -> updatesvc.exe is present in the data.",
      "evidence": [
        "de402144e2e4483f9c362c288c902d84ae7e326f3c0d69af6094e10f26907539",
        "a90de20f3af3b96b4a4c21e3253756271263130fec5733efa19839b4557ff9a0",
        "645f677d4b826a9d64672424995db4f1b32b53304fc81639e9fa0dde5eaea068",
        "6b1bfea712f8f2dec5d05b160d74da4465207655f7368ef072d12217692632d8",
        "b4c5e6c4d0b80684dc62aa48bdfcfd77cb67402024d5816cc5cee3e55ff72f7c",
        "ef57d88d8e8a71f4409b87efdb9292eb9a6b70c058d319e68a8ad4a81f381fda",
        "733742f9cdb0229651c72e17d4adb964dde5def02cf3ddd40ae89d67207331a4",
        "05ca445242f666728fdf7cfabf10846fd614b6de9144cb6baeceaa9c740b4ea6"
      ]
    },
    {
      "id": "p3",
      "order": 3,
      "tactic": "Persistence",
      "title": "Two redundant autostart mechanisms installed",
      "hosts": [
        "WKS-CORP-01"
      ],
      "techniques": [
        "T1547.001",
        "T1053.005"
      ],
      "start_utc": "2026-03-09T09:22:10.0000000Z",
      "end_utc": "2026-03-09T09:23:02.0000000Z",
      "summary": "A per-user Run value (SyncUpdater) and a scheduled task under a Microsoft-looking path (\\Microsoft\\Windows\\Sync\\SyncUpdateTask) both point at the same AppData binary. Security event 4698 independently corroborates the task registry artefact.",
      "evidence": [
        "07eca98642a761db9d28c792696f726e39ac67e5673f756e7675698aa536a24f",
        "79c501471539152fe57ed5bbd0c54e9902c541547c25f838f87a8dc2136f3b38",
        "736daa8e335b17bf6baccfb0cdfb5d2cedc97a0244992647fc63100d383a34b5"
      ]
    },
    {
      "id": "p4",
      "order": 4,
      "tactic": "Discovery",
      "title": "Off-hours host, group and forest-trust enumeration",
      "hosts": [
        "WKS-CORP-01",
        "DC-CORP-01"
      ],
      "techniques": [
        "T1033",
        "T1069.002",
        "T1482",
        "T1087.002",
        "T1018"
      ],
      "start_utc": "2026-03-10T02:05:11.0000000Z",
      "end_utc": "2026-03-10T02:14:10.0000000Z",
      "summary": "Between 02:05 and 02:15 the implant ran whoami /all, enumerated Domain Admins, and used nltest /domain_trusts to discover that eu.corp.example is a child of corp.example. A staged tool (adq.exe) then read 4,118 directory objects in 90 seconds, visible on DC-CORP-01 as bulk event-4662 activity sourced from 10.0.5.41.",
      "evidence": [
        "479bbed29448e4cad9b76809435f4273a429be302be6ced81a3a5443cebdc72d",
        "863c9f2fe20723d6b5b6589f3efe3cfe5209436c8ce92c53d9b24263db6bf989",
        "2b44d68b26aa56a255023597983fa045b71ac5f8c31bc4d38b785a64fd330cee",
        "d515440f105918d1fabe0fdda7b165851e958f6795963fe48f1759af42df05c1",
        "3f65fa34fb1b085a430c38428f2c55497b133331191384b025db5558667ee551",
        "d3e786ac5e0c789406a11a448e6ecf18090e94083d75673944cf78f8541ba0bb"
      ]
    },
    {
      "id": "p5",
      "order": 5,
      "tactic": "Credential Access",
      "title": "LSASS dumped and a service account kerberoasted",
      "hosts": [
        "WKS-CORP-01",
        "DC-CORP-01"
      ],
      "techniques": [
        "T1003.001",
        "T1558.003"
      ],
      "start_utc": "2026-03-10T02:31:19.0000000Z",
      "end_utc": "2026-03-10T02:52:31.0000000Z",
      "summary": "rundll32 invoked the comsvcs.dll MiniDump export against LSASS (pid 772), producing a 56 MB dump that YARA identifies from its minidump and lsasrv strings; Sysmon event 10 independently records the PROCESS_VM_READ handle. Twenty minutes later two RC4 service tickets were requested for EU\\svc-backup SPNs - the account that authenticates to the file server the following night.",
      "evidence": [
        "cc51804132c712d5c73901b6c1918a1c29e743847cd01f52787785062621f4f3",
        "f8d43e4300fee31c4e83ff9e05618c9af57cda010120134f46222a83461d8d0b",
        "c9fe88278696e76e149f8a8d1269ccdca3286ad8356eace642fd42c6b4ba78b7",
        "39730224a3ce10fdf8c0b1420a5050a14ed4d29b8855117adea564b83cf4e462",
        "6803206e2de5995d2695cf6b294d74a137671028232e9b93e6feab7aaa412c8f",
        "c84ab18c2dee3db4b3cc5c541a41de33627965a00c066e30cb637b03a34e0959"
      ]
    },
    {
      "id": "p6",
      "order": 6,
      "tactic": "Lateral Movement",
      "title": "Pivot to SRV-CORP-FS02 as EU\\svc-backup",
      "hosts": [
        "WKS-CORP-01",
        "SRV-CORP-FS02"
      ],
      "techniques": [
        "T1021.002",
        "T1078.002",
        "T1543.003",
        "T1569.002",
        "T1570",
        "T1071.001",
        "T1573.001"
      ],
      "start_utc": "2026-03-11T03:10:05.0000000Z",
      "end_utc": "2026-03-11T03:14:51.0000000Z",
      "summary": "The implant opened SMB to 10.0.5.20 as EU\\svc-backup; the file server records the matching type-3 logon from 10.0.5.41 four seconds later. The loader was copied in as C:\\Windows\\upd.exe with a SHA-256 identical to updatesvc.exe on the workstation, registered as the auto-start service SyncHostSvc, and began second-stage beaconing to sync-relay.example.",
      "evidence": [
        "0cc473c18c81651c1b3e4d8940aedca970f07cc26cda17499cdc9915e3fe7e92",
        "f91615ca69db13e1f017205ee86ad4f3f59fef17fe59b09d81341627848937b8",
        "253e72b162e4ec8b48405524d58368ad6e8cfd9a921b931105261d920bfa8df6",
        "e218c6139f5b53d94e81d75b834c8af5dae1c25a48086bf9dd3ece1afaf7e468",
        "422957041d957ec8d086c5fb5a41fb8c880770aac363fa6841d74f9ea8ff526b",
        "c87b4138df7c463f18066867592c00c92fc9e27b13cd7bb691316579210e6494"
      ]
    },
    {
      "id": "p7",
      "order": 7,
      "tactic": "Privilege Escalation",
      "title": "Cross-domain escalation from eu.corp.example to the forest root",
      "hosts": [
        "SRV-CORP-FS02",
        "DC-CORP-01"
      ],
      "techniques": [
        "T1134.005",
        "T1558.001",
        "T1003.006",
        "T1136.002",
        "T1098",
        "T1021.001",
        "T1078.002"
      ],
      "start_utc": "2026-03-12T01:32:14.0000000Z",
      "end_utc": "2026-03-12T01:52:40.0000000Z",
      "summary": "From the file server the attacker ran kt.exe with a SID-history argument naming the forest-root Enterprise Admins RID. DC-CORP-01 then logged a cross-realm ticket carrying that privileged ExtraSid, DS-Replication-Get-Changes-All exercised by a non-DC principal from 10.0.5.20, creation of CORP\\svc-support in the root domain, its addition to Enterprise Admins, and an RDP logon by that account eight minutes after it was created. This is the step the two-domain forest makes possible.",
      "evidence": [
        "877919bb4ec3ea76727b72083eeff3d9d55b40651bd65f9787cea58bca166919",
        "872d570a51d5eb4881248863e0d28b2d130c9c3dffe52e0ba82380b526d62bf5",
        "35f5e9f8c523eed19d7f4550ebe3e1793dcd8484c05995693d110df5699f70b8",
        "8c2c8aca2f65face882bbb7f82f43e765aaef544054781e13691b7a35641e5ef",
        "1d7b2d692a8e5f9f8ad706bb8fee5bb22f0dcd706e0c9daccffe84663f4f94fa",
        "c410debb43e0d8122afe85117b37b4cc64384b06713ed83a58ce4f0e32afb739",
        "d7c89fa9f7138736392a44c716208543588537f1541844e53589fed1560e53b5"
      ]
    },
    {
      "id": "p8",
      "order": 8,
      "tactic": "Collection and Exfiltration",
      "title": "3.4 GB of finance data staged and transferred out",
      "hosts": [
        "SRV-CORP-FS02"
      ],
      "techniques": [
        "T1560.001",
        "T1074.001",
        "T1041",
        "T1070.004"
      ],
      "start_utc": "2026-03-13T22:40:18.0000000Z",
      "end_utc": "2026-03-13T23:56:12.0000000Z",
      "summary": "A renamed archiver produced an encrypted-header archive of D:\\Finance\\2026Q1 in C:\\Windows\\Temp. The outbound transfer to files-transfer-node.example moved exactly 3,612,479,488 bytes - byte-for-byte the archive size - after which the archive was deleted, leaving the USN record behind.",
      "evidence": [
        "a1338591f744fca34d223ebede50a17358be8e631173c82fd0264a4db21fe425",
        "c90d32691767c1402e7bd3fe617c26a5cbd842fa1d0f64bbe0a10352f0033b5e",
        "3552e2b79a2625d6dea56c489ede0edf1c89356063dd9e80075654edd9845d6e",
        "daace936b2606b7985f3fdd86570e713a52fbc0954afbd2b6b38b59fd5fd8211"
      ]
    },
    {
      "id": "p9",
      "order": 9,
      "tactic": "Defense Evasion",
      "title": "Audit logs cleared and shadow copies destroyed",
      "hosts": [
        "SRV-CORP-FS02",
        "WKS-CORP-01",
        "DC-CORP-01"
      ],
      "techniques": [
        "T1070.001",
        "T1490",
        "T1070.004"
      ],
      "start_utc": "2026-03-14T00:12:41.0000000Z",
      "end_utc": "2026-03-14T00:31:12.0000000Z",
      "summary": "wevtutil cleared the Security channel on the file server (event 1102 is the last record before the gap), all volume shadow copies were deleted, the LSASS dump was removed from the workstation, and the forest-root DC audit log was cleared by the attacker-created account. Filesystem and USN artefacts survive on every host, which is why the acquisition still reconstructs the story.",
      "evidence": [
        "14b7d10d5fa24b80ce66ed13a3a91cefc80ac82392b7a7ceb31b7948fdb82b30",
        "c0da06181fe22c3c0f25d0d65249f6e29e0afeda261b8641916a7b0e0205c8d2",
        "f4d343d7b3b25932434f5b68deb3da5848fcde373ffcfb572136453b1bf50bc1",
        "18c30d7725aacd8b7f111e995952fbe33b4a4cee9d1fa406abae829abbfa2865",
        "9451ddf86e7042affcdde03da6f8ce47825612383c6dbe7a46f3db21d8ebcdba"
      ]
    }
  ]
};
