// Guards for the pre-authored demo forensic report (web/demo/report.js,
// generated by scripts/gen-demo-report.mjs).
//
// Why this file exists at all: loading web/demo/'s evidence gets an evaluator to
// a merged SuperTimeline, but the only route onward to a RENDERED report is an
// analysis run -- and the zero-cost mock provider deliberately returns an empty
// report. web/demo/report.js is the artifact that closes that gap, so it is a
// customer-facing deliverable and needs the same mechanical guards the payload
// has:
//
//  1. It is VALID: conforms to docs/report_schema.json (the contract itself, not
//     only the vendored copy) and passes the pipeline's own semantic validator.
//
//  2. Every CITATION RESOLVES. Findings and narrative phases cite rows by
//     row_hash; every one of those hashes must exist in web/demo/host-*.js. A
//     dangling citation renders as a broken reference, which in a customer
//     presentation is worse than no citation at all.
//
//  3. It is a GOOD report, not filler: severities span the range, the panels a
//     buyer actually looks at are populated, the deliberately-noisy detections
//     are dismissed with reasoning, and the analytic gaps are specific.
//
//  4. It is REGENERABLE and DETERMINISTIC: re-deriving it in-process produces
//     byte-identical output to the committed file, so the committed artifact can
//     never drift from the generator or from the payload it cites.
//
//  5. It is REACHABLE: this repo's signature defect is a finished engine no UI
//     path can reach, and a report nobody can load is the same bug.

import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import { validateAgainst } from '../assets/js/lib/validate-schema.js';
import { severityRank } from '../assets/js/lib/severity.js';
import { citationRate, sortFindings } from '../assets/js/report/metrics.js';
import { renderReport } from '../assets/js/report/render.js';
import { buildReportPdfBytes, resolveWatermarkText } from '../assets/js/report/pdf.js';
import { redactReport } from '../assets/js/redact/report.js';
import validateReport, { formatReportErrors } from '../assets/js/analysis/validate-report.js';
import { manifest } from '../demo/manifest.js';
import { report } from '../demo/report.js';
import { loadDemoRows, loadDemoReport, applyDemoReport } from '../assets/js/demo/index.js';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const WEB = path.join(HERE, '..');
const REPO = path.join(WEB, '..');
const REPORT_MODULE = path.join(WEB, 'demo', 'report.js');

// The generator is imported, not shelled out to: running the derivation
// in-process is what makes "byte-identical across two consecutive runs" and
// "the committed file matches the generator" the same assertion.
//
// Guarded, because this is a TOP-LEVEL await of a file OUTSIDE web/. An
// unguarded version threw ERR_MODULE_NOT_FOUND and took the entire test file
// down with it in the published repo, where scripts/ was not part of the publish
// set -- and because the Pages workflow runs `npm test` before deploying, that
// blocked the deploy (run #7). The generators are published now, so this path
// should not trigger; it stays so that a future change to the publish set
// degrades to a named skip instead of a whole suite vanishing.
let generator = null;
let generatorMissing = '';
try {
  generator = await import(pathToFileURL(path.join(REPO, 'scripts', 'gen-demo-report.mjs')).href);
} catch (err) {
  if (err?.code !== 'ERR_MODULE_NOT_FOUND') throw err;
  generatorMissing = 'scripts/gen-demo-report.mjs is not present in this checkout, so the '
    + 'regenerate-and-compare assertions cannot run here. Every other guard in this file still does.';
  // Loud on purpose: a silent skip is how a guard stops guarding without anyone
  // noticing. In the source repo the generator is always present, so seeing this
  // line at all means the publish set has changed.
  console.warn(`[demo-report.test] SKIPPING generator checks: ${generatorMissing}`);
}

/** Every demo row, and the set of hashes a citation may legally reference. */
const allRows = (await Promise.all(manifest.files.map((e) => loadDemoRows(e)))).flat();
const rowHashes = new Set(allRows.map((r) => r.row_hash));
const rowsByHash = new Map(allRows.map((r) => [r.row_hash, r]));

const ROW_HASH_RE = /^[0-9a-f]{64}$/;
const SEVERITIES = ['informational', 'low', 'medium', 'high', 'critical'];

// ---------------------------------------------------------------------------
// schema conformance
// ---------------------------------------------------------------------------

/** docs/report_schema.json uses {"$ref": "#/$defs/..."} for its ioc and
 * recommendation shapes, which lib/validate-schema.js does not resolve. Same
 * dereferencing analysis/validate-report.js performs, done locally so this test
 * can validate against the CONTRACT file in docs/ rather than the vendored
 * copy. */
function dereference(node, root, seen = new Set()) {
  if (Array.isArray(node)) return node.map((n) => dereference(n, root, seen));
  if (node && typeof node === 'object') {
    if (typeof node.$ref === 'string') {
      const name = /^#\/\$defs\/(.+)$/.exec(node.$ref)?.[1];
      assert.ok(name && root.$defs?.[name], `unsupported $ref ${node.$ref}`);
      if (seen.has(node.$ref)) return {};
      return dereference(root.$defs[name], root, new Set(seen).add(node.$ref));
    }
    return Object.fromEntries(Object.entries(node).map(([k, v]) => [k, dereference(v, root, seen)]));
  }
  return node;
}

describe('demo report: schema conformance', () => {
  test('validates against docs/report_schema.json, the contract itself', async () => {
    const contract = JSON.parse(await readFile(path.join(REPO, 'docs', 'report_schema.json'), 'utf8'));
    const errors = validateAgainst(dereference(contract, contract), report, '$');
    assert.deepEqual(
      errors.slice(0, 10).map((e) => `${e.path}: ${e.message}`),
      [],
      `${errors.length} schema violation(s) against docs/report_schema.json`,
    );
  });

  test('passes the pipeline\'s own validator, including the fabricated-citation check', async () => {
    const { valid, errors, skipped } = await validateReport(report, { rowHashes });
    assert.deepEqual(skipped, [], 'the fabricated-citation check must actually run — it is the point of this test');
    assert.ok(valid, `validateReport rejected the demo report:\n${formatReportErrors(errors)}`);
  });

  test('every required top-level key is present', () => {
    for (const key of ['schema_version', 'meta', 'scope', 'verdict', 'executive_summary', 'findings', 'dashboard', 'provenance']) {
      assert.ok(Object.hasOwn(report, key), `report is missing the required key "${key}"`);
    }
    assert.equal(report.schema_version, '1.0.0');
  });

  test('the persuasive optional panels are all populated', () => {
    // A customer demo with empty panels reads as a broken product, and several
    // of these are the most convincing parts of the tool.
    assert.ok(report.attack_narrative?.phases?.length >= 9, 'the narrative must carry every phase the dataset encodes');
    assert.ok(report.mitre_coverage.length >= 20, `expected a populated ATT&CK heatmap, got ${report.mitre_coverage.length} techniques`);
    assert.ok(report.analytic_gaps.length >= 5, 'analytic gaps are a first-class part of the report');
    assert.ok(report.dismissed_detections.length >= 5, 'the dataset ships five dismissible detections; all must be explained');
    assert.ok(report.recommendations.immediate.length > 0);
    assert.ok(report.recommendations.short_term.length > 0);
    assert.ok(report.recommendations.long_term.length > 0);
    assert.ok(report.recommendations.further_collection.length > 0, 'further_collection is the most valuable group when the collection is scoped');
    const iocTypes = Object.entries(report.iocs).filter(([, v]) => v.length > 0).map(([k]) => k);
    assert.ok(iocTypes.length >= 8, `expected >= 8 populated IOC categories, got ${iocTypes.join(', ')}`);
    assert.ok(report.executive_summary.text.split('\n\n').length >= 4, 'the executive summary must be several paragraphs, not a sentence');
    assert.ok(report.executive_summary.bullets.length > 0 && report.executive_summary.bullets.length <= 8);
  });
});

// ---------------------------------------------------------------------------
// citations
// ---------------------------------------------------------------------------

describe('demo report: every citation resolves to a real demo row', () => {
  test('every findings[].evidence[].row_hash exists in web/demo/host-*.js', () => {
    const dangling = [];
    let citations = 0;
    for (const f of report.findings) {
      assert.ok(f.evidence.length > 0, `${f.id}: an uncited finding is an opinion, not a finding`);
      for (const ev of f.evidence) {
        citations++;
        assert.match(ev.row_hash, ROW_HASH_RE, `${f.id}: malformed row_hash ${ev.row_hash}`);
        if (!rowHashes.has(ev.row_hash)) dangling.push(`${f.id} -> ${ev.row_hash}`);
      }
    }
    assert.deepEqual(dangling, [], 'citation(s) point at rows that exist in no host file');
    assert.ok(citations >= 40, `expected a densely cited report, got ${citations} citations`);
  });

  test('every evidence excerpt, host and timestamp matches the row it cites', () => {
    // A citation that resolves but misquotes is worse than a dangling one: it
    // looks authoritative. These fields exist so a renderer need not re-read the
    // timeline, so they must agree with it exactly.
    const problems = [];
    for (const f of report.findings) {
      for (const ev of f.evidence) {
        const row = rowsByHash.get(ev.row_hash);
        if (!row) continue;
        if (ev.host !== row.host) problems.push(`${f.id} ${ev.row_hash.slice(0, 8)}: host ${ev.host} != ${row.host}`);
        if (ev.timestamp_utc !== row.timestamp_utc) problems.push(`${f.id} ${ev.row_hash.slice(0, 8)}: timestamp mismatch`);
        if (ev.excerpt !== row.message) problems.push(`${f.id} ${ev.row_hash.slice(0, 8)}: excerpt is not the row's own message`);
        if (!ev.why_relevant) problems.push(`${f.id} ${ev.row_hash.slice(0, 8)}: no why_relevant`);
      }
    }
    assert.deepEqual(problems.slice(0, 10), [], 'evidence metadata disagrees with the cited rows');
  });

  test('every attack_narrative phase cites real rows on the hosts it names', () => {
    const problems = [];
    for (const phase of report.attack_narrative.phases) {
      assert.ok(phase.evidence.length > 0, `phase ${phase.order}: a phase with no evidence is a claim with no proof`);
      for (const ev of phase.evidence) {
        const row = rowsByHash.get(ev.row_hash);
        if (!row) problems.push(`phase ${phase.order} cites ${ev.row_hash}, which is in no host file`);
        else if (ev.excerpt !== row.message) problems.push(`phase ${phase.order}: excerpt is not the row's message`);
      }
    }
    assert.deepEqual(problems, [], 'the narrative points at evidence that does not exist');
  });

  test('every cross-reference by finding id resolves', () => {
    const ids = new Set(report.findings.map((f) => f.id));
    const bad = [];
    const check = (where, list) => {
      for (const id of list || []) if (!ids.has(id)) bad.push(`${where} -> ${id}`);
    };
    for (const p of report.attack_narrative.phases) check(`phase ${p.order}`, p.finding_ids);
    for (const m of report.mitre_coverage) check(`mitre ${m.technique_id}`, m.finding_ids);
    for (const [group, list] of Object.entries(report.recommendations)) {
      list.forEach((r, i) => check(`recommendations.${group}[${i}]`, r.finding_ids));
    }
    for (const [type, list] of Object.entries(report.iocs)) {
      list.forEach((ioc, i) => check(`iocs.${type}[${i}]`, ioc.finding_ids));
    }
    assert.deepEqual(bad, [], 'cross-reference(s) name a finding id that does not exist');
  });

  test('every IOC row_hash reference resolves too', () => {
    const bad = [];
    for (const [type, list] of Object.entries(report.iocs)) {
      for (const ioc of list) {
        for (const h of ioc.row_hashes || []) if (!rowHashes.has(h)) bad.push(`iocs.${type} ${ioc.value} -> ${h}`);
      }
    }
    assert.deepEqual(bad, [], 'IOC(s) reference rows that do not exist');
  });
});

// ---------------------------------------------------------------------------
// analytic quality
// ---------------------------------------------------------------------------

describe('demo report: it is a real incident report, not filler', () => {
  test('severities span the whole range and each finding carries a category and MITRE mapping', () => {
    const present = new Set(report.findings.map((f) => f.severity));
    for (const sev of SEVERITIES) {
      assert.ok(present.has(sev), `no ${sev}-severity finding — a demo where everything is critical teaches nothing about triage`);
    }
    for (const f of report.findings) {
      assert.ok(f.category, `${f.id}: no category`);
      assert.ok(f.narrative.length > 200, `${f.id}: narrative is too thin to read as analyst-written`);
      assert.ok(f.recommendation, `${f.id}: no recommendation`);
      for (const t of f.mitre_techniques || []) assert.match(t, /^T\d{4}(\.\d{3})?$/);
    }
    const categories = new Set(report.findings.map((f) => f.category));
    assert.ok(categories.size >= 8, `expected findings across >= 8 categories, got ${categories.size}`);
  });

  test('every MITRE technique a finding claims is one the rows\' own detections claim', () => {
    // The client detects; the report interprets. A finding asserting a technique
    // nothing in the evidence detected is the model (or an author) inventing
    // coverage.
    const detected = new Set(allRows.flatMap((r) => r.detections.flatMap((d) => d.mitre_techniques || [])));
    const invented = [...new Set(report.findings.flatMap((f) => f.mitre_techniques || []))].filter((t) => !detected.has(t));
    assert.deepEqual(invented, [], 'finding(s) claim ATT&CK techniques no detection in the data supports');
  });

  test('mitre_coverage is heatmap-ready and its max_severity agrees with the findings it references', () => {
    const byId = new Map(report.findings.map((f) => [f.id, f]));
    for (const entry of report.mitre_coverage) {
      assert.match(entry.technique_id, /^T\d{4}(\.\d{3})?$/);
      assert.ok(entry.technique_name, `${entry.technique_id}: charts.js labels cells with technique_name`);
      assert.ok(entry.tactic, `${entry.technique_id}: charts.js groups cells into tactic columns`);
      assert.ok(entry.event_count > 0, `${entry.technique_id}: zero events`);
      if (entry.finding_ids?.length) {
        let expected;
        for (const fid of entry.finding_ids) {
          const sev = byId.get(fid)?.severity;
          if (sev && (expected === undefined || severityRank(sev) > severityRank(expected))) expected = sev;
        }
        assert.equal(entry.max_severity, expected, `${entry.technique_id}: max_severity disagrees with ${entry.finding_ids.join(', ')}`);
      }
    }
    const tactics = new Set(report.mitre_coverage.map((m) => m.tactic));
    assert.ok(tactics.size >= 8, `expected >= 8 tactic columns in the heatmap, got ${tactics.size}`);
  });

  test('findings[].false_positive_considered is substantive REASONING, never a boolean', () => {
    // report_schema.json types this as a string: the benign explanation and how
    // to rule it out. Passing `true` burns both repair attempts and then fails
    // the run, and it has done so before.
    for (const f of report.findings) {
      assert.equal(typeof f.false_positive_considered, 'string', `${f.id}: false_positive_considered must be a string`);
      assert.ok(f.false_positive_considered.length > 80, `${f.id}: false_positive_considered must explain the benign reading, not name it`);
      assert.notEqual(f.false_positive_considered.trim().toLowerCase(), 'true');
    }
  });

  test('the dismissed detections are exactly the dataset\'s five low-fidelity ones, each with reasoning', () => {
    // Derived, not asserted from a list: the dismissible detections are exactly
    // the detection rows the manifest narrative does NOT cite. Demonstrating
    // that the tool rules noise OUT is a stronger sell than a report that treats
    // every alert as real.
    const cited = new Set(manifest.narrative.flatMap((p) => p.evidence));
    const noisyRuleIds = new Set(
      allRows
        .filter((r) => r.detection_count > 0 && !cited.has(r.row_hash))
        .flatMap((r) => r.detections.map((d) => d.rule_id)),
    );
    assert.equal(noisyRuleIds.size, 5, 'the dataset should ship exactly five dismissible detections');
    const dismissedIds = new Set(report.dismissed_detections.map((d) => d.rule_id));
    assert.deepEqual([...dismissedIds].sort(), [...noisyRuleIds].sort(), 'the dismissed set must be exactly the un-narrated detections');

    // And none of them may be a detection the findings rely on.
    const supporting = new Set(report.findings.flatMap((f) => (f.detection_rules || []).map((d) => d.rule_id)));
    for (const id of dismissedIds) {
      assert.ok(!supporting.has(id), `${id} is both dismissed as benign and cited in support of a finding`);
    }
    for (const d of report.dismissed_detections) {
      assert.ok(d.engine && d.rule_name, `${d.rule_id}: dismissal must name the engine and rule`);
      assert.ok(d.occurrences > 0, `${d.rule_id}: occurrences must be counted from the data`);
      assert.ok(d.rationale.length > 120, `${d.rule_id}: "benign" without reasoning a reviewer can challenge is not a dismissal`);
      assert.ok(['low', 'moderate', 'high'].includes(d.confidence), `${d.rule_id}: dismissal needs a confidence`);
    }
  });

  test('analytic gaps are specific and honest about what a three-host collection cannot show', () => {
    for (const g of report.analytic_gaps) {
      assert.ok(g.gap.length > 40, 'a one-line gap is a placeholder');
      assert.ok(g.reason, `"${g.gap}": every gap needs a machine-readable reason`);
      assert.ok(g.detail.length > 80, `"${g.gap}": needs enough detail to be actionable`);
      assert.ok(g.how_to_close, `"${g.gap}": a gap with no route to closing it is not useful`);
    }
    const reasons = new Set(report.analytic_gaps.map((g) => g.reason));
    assert.ok(reasons.size >= 4, `gaps should span several reasons, got ${[...reasons].join(', ')}`);
    // The deliberately-uncollected child DC is the honest centrepiece: the
    // manifest says it is referenced by evidence but never collected.
    const blob = JSON.stringify(report.analytic_gaps);
    assert.match(blob, /DC-EU-01/, 'the gaps must name the child-domain controller that was not collected');
    assert.match(blob, /evidence_not_collected/);
    assert.match(blob, /anti_forensics_suspected/, 'the attacker cleared three audit logs; that bounds the report and must be stated');
  });

  test('scope and dashboard agree with the payload, and nothing was sampled away', () => {
    assert.equal(report.scope.row_count, allRows.length, 'scope.row_count must be the real row count');
    assert.equal(report.scope.rows_analysed, allRows.length, 'the demo analyses every row; a sampling caveat here would be false');
    assert.equal(report.scope.hosts.length, manifest.files.length);
    for (const h of report.scope.hosts) {
      const entry = manifest.files.find((e) => e.host === h.host);
      assert.ok(entry, `scope names an undeclared host ${h.host}`);
      assert.equal(h.row_count, entry.row_count);
      assert.equal(h.os, entry.os);
    }
    const sevSum = Object.values(report.dashboard.severity_distribution).reduce((a, b) => a + b, 0);
    assert.equal(sevSum, allRows.length, 'severity_distribution must account for every row');
    assert.ok(report.dashboard.events_over_time.length > 0);
    assert.ok(report.dashboard.entity_graph.nodes.length > 0 && report.dashboard.entity_graph.edges.length > 0);
    assert.equal(report.provenance.rows_omitted, 0);
  });

  test('the report is honest that it was authored rather than model-generated', () => {
    // A customer-facing mockup that implies an LLM wrote it would be a
    // misrepresentation. report_schema.json's provider enum includes "mock" for
    // exactly this.
    assert.equal(report.meta.model.provider, 'mock');
    assert.equal(report.meta.usage.estimated_cost_usd, 0);
    assert.equal(report.meta.usage.input_tokens, 0);
    assert.match(report.meta.engagement.description, /SYNTHETIC/i);
    assert.match(JSON.stringify(report.provenance.warnings), /pre-authored/i);
    assert.match(report.meta.engagement.classification, /SYNTHETIC/i);
  });
});

// ---------------------------------------------------------------------------
// renderers
// ---------------------------------------------------------------------------

describe('demo report: every renderer handles it', () => {
  test('citationRate() reports full coverage as an OBJECT, not a number', () => {
    // citationRate() returns {cited,total,rate} and rate is null when there are
    // no findings. Treating it as a number is a documented past defect.
    const rate = citationRate(report);
    assert.equal(typeof rate, 'object');
    assert.equal(rate.total, report.findings.length);
    assert.equal(rate.cited, report.findings.length, 'every demo finding is cited, so the rate must be 1');
    assert.equal(rate.rate, 1);
  });

  test('findings are already ordered the way the renderers sort them', () => {
    const expected = sortFindings(report.findings).map((f) => f.id);
    assert.deepEqual(report.findings.map((f) => f.id), expected, 'emit findings in the pipeline\'s own severity/confidence order');
  });

  test('renderReport() emits the attack-narrative anchor mountDashboard() needs', () => {
    // report/main.js's mountDashboard() anchors the ENTIRE dashboard and entity
    // graph on [data-testid="attack-narrative"]. A report that lost that anchor
    // silently rendered with no charts at all.
    const html = renderReport(report);
    for (const id of ['report-header', 'verdict-panel', 'executive-summary', 'findings-section',
      'attack-narrative', 'ioc-panel', 'analytic-gaps', 'dismissed-detections', 'recommendations']) {
      assert.match(html, new RegExp(`data-testid="${id}"`), `renderReport() did not emit the ${id} section`);
    }
    assert.ok(html.includes('data-testid="finding-card"'), 'no finding cards rendered');
    assert.doesNotMatch(html, /data-testid="uncited-badge"/, 'no finding should render as UNCITED');
    // Phase buttons drive the cross-filter; one per narrative phase.
    const phaseButtons = html.match(/class="phase-item"/g) || [];
    assert.equal(phaseButtons.length, report.attack_narrative.phases.length);
  });

  test('the PDF exporter produces a real PDF from it, with the synthetic watermark', async () => {
    const watermark = resolveWatermarkText(report);
    assert.match(watermark, /SYNTHETIC/i, 'the watermark must mark the demo output as synthetic');
    const { bytes, pageCount, watermarkText } = await buildReportPdfBytes(report);
    assert.equal(watermarkText, watermark);
    assert.ok(pageCount >= 5, `a 14-finding report should run to several pages, got ${pageCount}`);
    assert.ok(bytes.length > 20000, `PDF is implausibly small (${bytes.length} bytes)`);
    assert.equal(String.fromCharCode(...bytes.subarray(0, 5)), '%PDF-');
    assert.equal(String.fromCharCode(...bytes.subarray(bytes.length - 6)).trim(), '%%EOF');
  });

  test('the redaction gate treats it like any other report', async () => {
    // redact/index.js's loadCatalog() fetch()es assets/data/sensitive-data.json,
    // and Node refuses fetch() on a file: URL ("not implemented... yet"). Stub
    // fetch with a disk read for the duration of the test rather than reaching
    // into the redaction module, so this exercises the real redactReport() path
    // the export buttons use.
    const realFetch = globalThis.fetch;
    globalThis.fetch = async (url) => new Response(await readFile(new URL(url), 'utf8'), {
      status: 200, headers: { 'content-type': 'application/json' },
    });
    try {
      const none = await redactReport(report, { profile: 'none' });
      assert.equal(none.redacted, false, '"none" must be a provable no-op');
      assert.equal(none.report, report, '"none" must hand back the very same object');

      const published = await redactReport(report, { profile: 'publish', keyHex: '11'.repeat(32) });
      assert.equal(published.redacted, true);
      assert.ok(published.report.redaction, 'a redacted export must carry its redaction record');
      assert.equal(published.report.findings.length, report.findings.length, 'redaction must not drop findings');
      assert.notEqual(
        published.report.scope.hosts[0].host,
        report.scope.hosts[0].host,
        'the publish profile must pseudonymise host identity',
      );
    } finally {
      globalThis.fetch = realFetch;
    }
  });
});

// ---------------------------------------------------------------------------
// the generator
// ---------------------------------------------------------------------------

describe('the generator is deterministic and the committed file is not stale', () => {
  test('two consecutive derivations produce byte-identical module source', { skip: generatorMissing || false }, async () => {
    const first = generator.reportModuleSource((await generator.buildReport()).report);
    const second = generator.reportModuleSource((await generator.buildReport()).report);
    assert.equal(first, second, 'scripts/gen-demo-report.mjs is not deterministic');
    assert.ok(first.length > 10000);
  });

  test('web/demo/report.js matches what the generator produces right now', { skip: generatorMissing || false }, async () => {
    const { report: rebuilt, payload } = await generator.buildReport();
    const expected = generator.reportModuleSource(rebuilt);
    // core.autocrlf means the working tree may hold CRLF while the generator
    // writes LF; normalise before comparing bytes.
    const committed = (await readFile(REPORT_MODULE, 'utf8')).replace(/\r\n/g, '\n');
    assert.equal(committed, expected, 'web/demo/report.js is stale — run: node scripts/gen-demo-report.mjs');
    // Compared through JSON, not with deepStrictEqual on the live objects:
    // computeDashboard() sets `network_endpoints[].domain`/`.ip` explicitly to
    // undefined for endpoints that have only the other, and JSON.stringify drops
    // an undefined-valued key entirely. So the loaded module legitimately lacks
    // keys the freshly-derived object has present-but-undefined, and
    // deepStrictEqual calls that a difference. The serialised form is the
    // artifact that ships, so it is the right thing to compare.
    assert.deepEqual(JSON.parse(JSON.stringify(rebuilt)), report, 'the committed module does not match a fresh derivation');
    assert.equal(payload.allRows.length, allRows.length);
  });

  test('the generator refuses to emit a report with a dangling citation', { skip: generatorMissing || false }, async () => {
    // The guard that matters most, exercised rather than assumed: corrupt one
    // citation and checkReport() must reject it.
    const { report: fresh, payload } = await generator.buildReport();
    await generator.checkReport(fresh, payload); // the clean case passes
    const broken = structuredClone(fresh);
    broken.findings[0].evidence[0].row_hash = 'f'.repeat(64);
    await assert.rejects(
      () => generator.checkReport(broken, payload),
      /exists in no web\/demo\/host-\*\.js row/,
      'a fabricated citation must be a hard generation failure',
    );
  });

  test('the generated module declares itself generated and synthetic', async () => {
    const head = (await readFile(REPORT_MODULE, 'utf8')).slice(0, 600);
    assert.match(head, /GENERATED FILE/);
    assert.match(head, /gen-demo-report\.mjs/, 'the module must name the generator that produces it');
    assert.match(head, /gen-demo-dataset\.mjs/, 'and the generator that produced the evidence it analyses');
    assert.match(head, /SYNTHETIC DATA ONLY/);
  });
});

// ---------------------------------------------------------------------------
// safe to publish
// ---------------------------------------------------------------------------

describe('demo report: safe to publish', () => {
  test('contains no real-looking identifiers', () => {
    const blob = JSON.stringify(report);

    // The exact leak scripts/publish-web.sh gates on, which has caught a real
    // one before.
    const realHost = os.hostname();
    if (realHost && realHost.length >= 4) {
      assert.ok(!blob.toLowerCase().includes(realHost.toLowerCase()), `this machine's hostname (${realHost}) appears in the demo report`);
    }
    for (const h of report.scope.hosts) {
      assert.match(h.host, /^(WKS|SRV|DC)-CORP-[A-Z]{0,3}\d{2}$/, `${h.host} is not an obviously synthetic hostname`);
    }
    for (const ioc of report.iocs.ip_addresses) {
      assert.match(ioc.value, /^(192\.0\.2|198\.51\.100|203\.0\.113)\./, `${ioc.value} is not an RFC 5737 documentation address`);
    }
    for (const ioc of report.iocs.domains) {
      assert.match(ioc.value, /\.example$/, `${ioc.value} does not use the RFC 2606 reserved .example TLD`);
    }
    for (const ioc of report.iocs.urls) {
      assert.match(new URL(ioc.value).hostname, /\.example$/);
    }
    assert.doesNotMatch(blob, /https?:\/\/[a-z0-9.-]+\.(com|net|org|io|ru|cn|co\.uk)\b/i);
    assert.doesNotMatch(blob, /@[a-z0-9.-]+\.(com|net|org|io|ru|cn|co\.uk)\b/i);
  });

  test('no absolute-root path in the report payload or the demo loader', async () => {
    // Mirrors the gate in scripts/publish-web.sh: Pages serves this project from
    // /DFIR/, so '/demo/report.js' resolves to the user root and 404s in
    // production while working perfectly on a local server.
    for (const file of [REPORT_MODULE, path.join(WEB, 'assets', 'js', 'demo', 'index.js'), path.join(WEB, 'assets', 'js', 'demo', 'panel.js')]) {
      const src = await readFile(file, 'utf8');
      const hits = src.match(/(?:from|import|fetch\(|new URL\()\s*['"]\/[^/]/g);
      assert.equal(hits, null, `${path.basename(file)} uses an absolute-root path: ${hits?.join(', ')}`);
    }
  });

  test('the payload is an ES module, not a JSON file fetched at runtime', async () => {
    // fetch() of a sibling file is blocked from file://, which the docs tell
    // analysts to use for air-gapped work; a dynamic import() is not.
    const src = await readFile(REPORT_MODULE, 'utf8');
    assert.match(src, /^export const report = \{/m, 'report.js must export the report object directly');
    const loader = await readFile(path.join(WEB, 'assets', 'js', 'demo', 'index.js'), 'utf8');
    assert.match(loader, /import\(new URL\('report\.js', DEMO_BASE\)\.href\)/, 'the loader must dynamic-import the module');
    assert.doesNotMatch(loader, /fetch\(\s*new URL\('report/, 'the loader must not fetch() the payload');
  });

  test('web/demo stays small enough for a one-click load over Pages', async () => {
    const { stat, readdir } = await import('node:fs/promises');
    let bytes = 0;
    const dir = path.join(WEB, 'demo');
    for (const name of await readdir(dir)) bytes += (await stat(path.join(dir, name))).size;
    assert.ok(bytes < 6 * 1024 * 1024, `web/demo is ${(bytes / 1048576).toFixed(1)} MB; keep it under 6 MB`);
  });
});

// ---------------------------------------------------------------------------
// reachability from the UI
// ---------------------------------------------------------------------------

describe('the demo report is reachable from the UI', () => {
  test('the loader exposes it and can put it on a store', async () => {
    const loaded = await loadDemoReport();
    assert.equal(loaded.meta.report_id, report.meta.report_id, 'loadDemoReport() must resolve the committed module');
    const writes = [];
    const fakeStore = { set: (patch) => writes.push(patch) };
    const returned = applyDemoReport(loaded, { store: fakeStore });
    assert.equal(returned, loaded);
    assert.deepEqual(writes, [{ report: loaded }], 'applyDemoReport() must write state.report and nothing else');
  });

  test('the demo panel offers a labelled, wired second button', async () => {
    const src = await readFile(path.join(WEB, 'assets', 'js', 'demo', 'panel.js'), 'utf8');
    assert.match(src, /'Load demo report'/, 'the button must carry visible label text');
    assert.match(src, /dataset\.testid = 'load-demo-report'/, 'the button needs a stable test id');
    assert.match(src, /reportBtn\.addEventListener\('click'/, 'the button must be wired to a handler');
    assert.match(src, /reportBtn\.disabled = false/, 'the button must become enabled once the payload is available');
    assert.match(src, /loadDemoReport/, 'the panel must use the loader rather than importing the payload itself');
    // The EVIDENCE must still travel through the real ingest path; only a
    // finished report (which has no parser, merge or detection stage) bypasses
    // it, and it does so through the loader, not through the panel.
    assert.match(src, /onFiles\(files\)/, 'the evidence button must still hand File objects to the ingest view');
  });

  test('the Report view can load it from its empty state without weakening the redaction gate', async () => {
    const src = await readFile(path.join(WEB, 'assets', 'js', 'views', 'report.js'), 'utf8');
    assert.match(src, /from '\.\.\/demo\/index\.js'/, 'report.js must import the demo loader');
    assert.match(src, /'Load demo report'/, 'the empty state must offer a labelled button');
    assert.match(src, /dataset\.testid = 'load-demo-report-view'/);
    assert.match(src, /demoActions\(\)/, 'the button must actually be appended to the empty state');
    // The demo path writes state.report and nothing else, so every export still
    // funnels through forExport(). views-wired.test.mjs owns that invariant;
    // this is the local guard that the demo entry point did not sneak past it.
    assert.match(src, /store\.set\(\{ report: await loadDemoReport\(\) \}\)/, 'the demo path must write state.report, not export anything itself');
    assert.ok((src.match(/forExport\(/g) || []).length >= 4, 'the redaction gate must still be used by every export path');
  });
});

// ---------------------------------------------------------------------------
// Export filename: see tests/case-slug.test.mjs for the full guard.
// ---------------------------------------------------------------------------
// Both pages name exports after the case id and each used to carry its own copy
// of that logic, which drifted twice: the console read a field the schema does
// not define (`meta.case_id` rather than `meta.engagement.case_id`), and after
// that was fixed the two sanitised differently ('-' here, '_' there). Both are
// now resolved by sharing ONE implementation, lib/case-slug.js, which is where
// the behavioural tests live. All that belongs here is the demo-specific fact.
describe('the demo report exports under its own case id', () => {
  test('caseSlug derives DEMO-2026-0317, so both pages name the file identically', async () => {
    const { caseSlug } = await import('../assets/js/lib/case-slug.js');
    const { report } = await import('../demo/report.js');
    assert.equal(report.meta.engagement.case_id, 'DEMO-2026-0317');
    assert.equal(caseSlug(report), 'DEMO-2026-0317');
    // Before the fix this was `report-forensic-report.pdf` from the console and
    // `DEMO-2026-0317-forensic-report.pdf` from report.html.
    assert.equal(`${caseSlug(report)}-forensic-report.pdf`, 'DEMO-2026-0317-forensic-report.pdf');
  });
});
